# Generated by Django 4.2.1 on 2023-07-03 19:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('num_Cours', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_Cours', models.CharField(max_length=60)),
                ('masse_horaire', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['nom_Cours'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('CIN', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('titre_prof', models.CharField(blank=True, max_length=60, null=True)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cv', models.FileField(default=None, upload_to='cv')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='EnseignantRecrutement',
            fields=[
                ('CIN', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('titre_prof', models.CharField(blank=True, max_length=60, null=True)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cv', models.FileField(default=None, upload_to='cv')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('CNE', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=80)),
                ('adresse', models.CharField(max_length=100)),
                ('annee_Bac', models.IntegerField()),
                ('parcours', models.CharField(choices=[('Bac +2', 'Bac +2'), ('Bac +3', 'Bac +3'), ('Bac +5', 'Bac +5')], max_length=20)),
            ],
            options={
                'ordering': ['CNE'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('num_Module', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_Module', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['nom_Module'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('num_Option', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_Option', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['nom_Option'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('nom_Salle', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['nom_Salle'],
            },
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('id_S', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NoteEtudiant',
            fields=[
                ('id_Note', models.BigAutoField(primary_key=True, serialize=False)),
                ('note_Module', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('resultat', models.CharField(choices=[('R', 'Rattrapage'), ('V', 'validé'), ('X', 'échec')], max_length=1)),
                ('CNE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Ecole.etudiant')),
                ('num_Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Ecole.module')),
            ],
            options={
                'ordering': ['CNE'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='code_Option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Ecole.option'),
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id_Horaire', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_Debut_C', models.DateTimeField()),
                ('date_Fin_C', models.DateField()),
                ('CIN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Ecole.enseignant')),
                ('num_Cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Ecole.cours')),
                ('num_Salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Ecole.salle')),
            ],
            options={
                'ordering': ['date_Debut_C'],
            },
        ),
        migrations.CreateModel(
            name='EtudiantInscription',
            fields=[
                ('CNE', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=80)),
                ('adresse', models.CharField(max_length=100)),
                ('annee_Bac', models.IntegerField()),
                ('parcours', models.CharField(choices=[('2', 'Bac +2'), ('3', 'Bac +3'), ('5', 'Bac +5')], max_length=20)),
                ('code_Option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Ecole.option')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='code_Option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Ecole.option'),
        ),
        migrations.AddField(
            model_name='cours',
            name='num_Enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Ecole.enseignant'),
        ),
        migrations.AddField(
            model_name='cours',
            name='num_Module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Ecole.module'),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('num_Abs', models.BigAutoField(primary_key=True, serialize=False)),
                ('etat_abs', models.CharField(choices=[('E', 'Excusé(e)'), ('J', 'justifiée'), ('N', 'Non justifié')], max_length=1)),
                ('date_abs', models.DateTimeField()),
                ('CNE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Ecole.etudiant')),
                ('num_Cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Ecole.cours')),
            ],
            options={
                'ordering': ['date_abs'],
            },
        ),
    ]
