# Generated by Django 4.2.1 on 2023-07-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Ecole', '0004_alter_login_user_cin_alter_login_user_cne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='date_Fin_C',
            field=models.DateTimeField(),
        ),
    ]
