# Generated by Django 4.2.1 on 2023-07-05 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Ecole', '0005_alter_horaire_date_fin_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='CIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Ecole.enseignant'),
        ),
    ]
